<?php /** @inc kije\Formgenerator\Formgenerator $this */ ?>
<!doctype>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Example-Form</title>
</head>

<body>
<?php echo '<pre>' . print_r($_POST, true) . '</pre>'; ?>
<?php if ($show_form): ?>
    <form action="<?php echo $action; ?>" method="<?php echo $method; ?>">
        <dl>
            <?php foreach ($this->getFormfields() as $formfield) { ?>
                <dt>
                    <label for="<?php echo $formfield->getTag()->get('id'); ?>">
                        <?php echo $formfield->getCaption(); ?>
                    </label>
                </dt>
                <dd>
                    <?php echo $formfield->getTag()->toHTML(); ?>
                </dd>
            <?php } ?>
        </dl>
    </form>
<?php endif; ?>
</body>
</html>